name: Deploy Flutter Web to InfinityFree

on:
  push:
    branches: [ "main" ] # Sesuaikan dengan nama branch utama GitHub Anda (main atau master)

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Sesuaikan dengan versi Flutter Anda
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web release
        run: flutter build web --release

      - name: Sync files to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/web/
          server-dir: htdocs/ # Folder tujuan di hosting Anda